export const cities = [
  { name: "Paris" },
  { name: "Rio de Janeiro" },
  { name: "Aracaju" },
  { name: "Gramado" },
  { name: "New York" },
  { name: "Tokyo" },
  { name: "London" },
  { name: "Berlin" },
  { name: "Salvador" },
  { name: "Buenos Aires" },
  { name: "Seoul" },
  { name: "Bangkok" },
  { name: "Los Angeles" },
  { name: "Toronto" },
  { name: "Dubai" },
  { name: "Singapore" },
  { name: "Madrid" },
  { name: "Rome" },
  { name: "Amsterdam" },
  { name: "Lisbon" },
];
